config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'welcome', to: 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'member/add', to: 'members#add'
  post 'member/create', to: 'members#create'
  get 'member/lists', to: 'members#lists'
  get 'access/create' to: 'access#create'
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :  Member
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates :mem_name, :mem_email, :mem_pwd, :presence => true
  validates :mem_name, :length => {:minimum => 2, :maximum => 5}

  after_initialize do |member|
    puts "Model Initialized!"
  end

end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def create()
    {
      
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  def add()
    #@showdata="add method initialized"
    @member = Member.new
    #@member.mem_name="name"
    #@member.mem_email="eamil@email.com"
    #@member.mem_pwd="123123"
    #puts @member.save
  end
  def create()
    @member = Member.new
    @member.mem_name= params[:mem_name]
    @member.mem_email=params[:mem_email]
    @member.mem_pwd=params[:mem_pwd]
      
    @member.save
    @error=@member.errors[:mem_name].any?
  end
  def lists()
    @lists = Member.select("mem_name, mem_email").order("mem_name")
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access/create.html.erb
<h1> Create Member Accesses </h1>

<%= form_tag(controller:'access',action:"assign",method:"post") do %>
<%= label_tag(:member_id,Choose Member) %>
<%= select_tag(:member_id,options_for_select([
    [val1,1],
    [val2,2],
    [val3,3]
])) %>
<%= submit_tag('create roles')%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/add.html.erb
<h3>Add New Member</h3>

<%= @showdata %>
<%= form_tag(controller:'members',action:'create',method:'post') do %>
  <%= label_tag(:mem_name,"Member Name") %><br/>
  <%= text_field_tag(:mem_name) %><br/><br/>

  <%= label_tag(:mem_email,"Member Email") %><br/>
  <%= text_field_tag(:mem_email) %><br/><br/>

  <%= label_tag(:mem_pwd,"Member Password") %><br/>
  <%= text_field_tag(:mem_pwd) %><br/><br/>

  <%= submit_tag('Add Member')%>
<% end %>

app/views/members/create.html.erb
<% @member.errors.full_messages.each do |msg| %>
  <%= msg %><br/>
<% end  %> 
<%= @error %>

app/views/members/lists.html.erb
<h2>Members list</h2>
<table>
<% @lists.each do |mem| %>
  <tr>
  <td><%= mem.mem_name %></td>
  <td><%= mem.mem_email %></td>
  </tr>
<% end %>  
</table>  

app/views/welcome/about.html.erb
<h1>About page</h1>

<%= link_to "Home", welcome_path %>

app/views/welcome/home.html.erb
<h1>First ROR Controller</h1>

<%= link_to 'About', about_path, :id=>"Home", :class=>"btn" %>